### ISSUE TITLE
[SCSS] Wrong syntax highlighting

### ISSUE THREAD

**Issue by jfcherng** [braver/SublimeSass#113]
![Image](https://github.com/user-attachments/assets/e58d0922-20b9-4022-9bf1-069856754c30)

```scss
ul:has(> li),
a[ng-click='post()'] {
/*               ^ wrong highlighting */
  font-size: 20px;
}
```
