### ISSUE TITLE
Strings inside interpolation

### ISSUE THREAD

**Issue by sandrojohanides** [braver/SublimeSass#36]
See `'('` and `')'`, highlight is missing for both quotes and their content? But maybe it’s impossible to do.

![screen shot 2018-11-26 at 10 35 35](https://user-images.githubusercontent.com/8327913/49011635-39ec7480-f177-11e8-9dc3-1584a924c38f.png)
```scss
@mixin a-hidden($span, $axis, $aim) {
	transform: #{translate + $axis + '(' + $span * $aim + ')'};
	opacity: 0;
}
```
