### ISSUE TITLE
Vendor pseudo classes

### ISSUE THREAD

**Issue by sandrojohanides** [braver/SublimeSass#38]
Type selector (`input`/`button`) should be red for my color scheme, pseudo selectors white (with grey vendor part maybe).

![screen shot 2018-11-26 at 10 37 16](https://user-images.githubusercontent.com/8327913/49011980-46bd9800-f178-11e8-834e-598404316f70.png)
```scss
input:-webkit-autofill,
input:-webkit-autofill:hover,
input:-webkit-autofill:focus {
	box-shadow: inset 0 0 0 100px color(white);
}
```
![screen shot 2018-11-26 at 12 43 50](https://user-images.githubusercontent.com/8327913/49012243-1e826900-f179-11e8-96af-0469d24028c9.png)
```scss
button:-moz-focusring,
[type="button"]:-moz-focusring,
[type="reset"]:-moz-focusring,
[type="submit"]:-moz-focusring {
  outline: 1px dotted ButtonText;
}
```
