### ISSUE TITLE
Vendor pseudo elements

### ISSUE THREAD

**Issue by sandrojohanides** [braver/SublimeSass#39]
Vendor parts of pseudo elements are grey, please close if on purpose.

![screen shot 2018-11-26 at 10 38 13](https://user-images.githubusercontent.com/8327913/49012108-b7fd4b00-f178-11e8-84cb-f4da8dec61c1.png)
```scss
input[type="number"]::-webkit-inner-spin-button,
input[type="number"]::-webkit-outer-spin-button {
	appearance: none;
}

input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-decoration {
	appearance: none;
}

input::-ms-clear,
input::-ms-reveal {
	display: none;

	width: 0;
	height: 0;
}
```
