### ISSUE TITLE
Last item in a list named as a CSS property

### ISSUE THREAD

**Issue by sandrojohanides** [braver/SublimeSass#42]
Seems to happen in a comma separated list when a string is named as a CSS property (`bottom`, `color`...). In a space separated list, all of the property-like strings are incorrectly highlighted. Doesn’t work for all properties, see `position`.

![screen shot 2018-11-26 at 13 06 35](https://user-images.githubusercontent.com/8327913/49013192-314a6d00-f17c-11e8-8443-adddcf7b9bbd.png)
![screen shot 2018-11-26 at 12 48 35](https://user-images.githubusercontent.com/8327913/49012974-75893d80-f17b-11e8-80a6-6a770efb3efb.png)
```scss
@if index((top, bottom), $dir) {
	$offset-dir: if($offset-dir == right, right, left);
} @else if index((left, right), $dir) {
	$offset-dir: if($offset-dir == bottom, bottom, top);
}
```
