### ISSUE TITLE
Default values inside var() function

### ISSUE THREAD

**Issue by sandrojohanides** [braver/SublimeSass#43]
`calc()` doesn’t seem to matter in this case, values such as `0` or `0em` are not of correct color.

![screen shot 2018-11-26 at 13 01 33](https://user-images.githubusercontent.com/8327913/49013271-766e9f00-f17c-11e8-9301-b55793238c9e.png)
```scss
padding-left: calc(
	var(--depth, 0) * #{$folder-list-padding} +
	var(--not-checkable, #{$folder-list-padding}) +
	var(--padding-left, 0em)
);
```
