### ISSUE TITLE
'to' in linear-gradient()

### ISSUE THREAD

**Issue by sandrojohanides** [braver/SublimeSass#47]
It seems GitHub does the same but I don’t know if it’s correct.

![screen shot 2018-11-27 at 13 11 55](https://user-images.githubusercontent.com/8327913/49081127-12b0a880-f246-11e8-8e1f-2ca598be130d.png)
```scss
.test {
  background-image: linear-gradient(to right, white, black);
}
```
