### ISSUE TITLE
:-moz-focusring after other than type selectors

### ISSUE THREAD

**Issue by sandrojohanides** [braver/SublimeSass#50]
`-moz-` part of the pseudo class is not highlighted, but is in the pseudo element. It also is highlighed after a type selector, such as `button`.

![screen shot 2018-11-27 at 13 52 44](https://user-images.githubusercontent.com/8327913/49083084-d8e2a080-f24b-11e8-8f0a-96cdf8837a68.png)
```scss
button::-moz-focus-inner,
[type="button"]::-moz-focus-inner,
[type="reset"]::-moz-focus-inner,
[type="submit"]::-moz-focus-inner {
  border-style: none;
  padding: 0;
}

/**
 * Restore the focus styles unset by the previous rule.
 */

button:-moz-focusring,
[type="button"]:-moz-focusring,
[type="reset"]:-moz-focusring,
[type="submit"]:-moz-focusring {
  outline: 1px dotted ButtonText;
}
```
