### ISSUE TITLE
Goto definitions (2.3.8)

### ISSUE THREAD

**Issue by KubaJastrz** [braver/SublimeSass#57]
I'm not sure if I'm missing something, but go to symbol functionality stopped working a while ago.

Here's how it looks in the v2.3.8:
![2019-01-15_20-40-57](https://user-images.githubusercontent.com/6443113/51205313-ea6c2e80-1905-11e9-9c65-728c3833ea3e.png)

I tracked down the #32 issue and e5d82f41b7f46cea41de53448777f433cf861cb6 that was supposedly fixing it. But I believe that the core of the problem lays in b048ae6707dccf8b80dabb7ae955de59530e474c, where Symbol definitions where removed completely.

**Comment by KubaJastrz** [comment]
I've made simple test case similiar to one above:
```scss
$div: div;

.one {
    &__two { color: #000; }
}

.three { color: #000; }

#four { color: #000; }

#{$div} { color: #000; }

.#{$div} { color: #000; }

##{$div} { color: #000; }

span { color: #000; }
```

Here is `.tmPreferences` file that targets all of them (except `#{$div}`):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Goto Symbol</string>
    <key>scope</key>
    <string>meta.selector.css (entity.other.attribute-name, entity.other.attribute-name.id, entity.other.attribute-name.class)</string>
    <key>settings</key>
    <dict>
      <key>showInSymbolList</key>
      <integer>1</integer>
    </dict>
  </dict>
</plist>
```

Preview:
![2019-01-15_21-03-04](https://user-images.githubusercontent.com/6443113/51206685-fa394200-1908-11e9-9d4b-3bdb3ddf0119.png)
